### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by birbilis**
my first try at a pull request, having first forked the repository into my own and committed the changes to mine, then doing compare and pull request into the original repository

### CODE REVIEW

**Comment by birbilis** [comment]
when I click on "small code cleanup" entry above it says " Showing 3 changed files  with 1,064 additions and 1,064 deletions." which worries me

**Comment by birbilis** [comment]
even for the other entry about a small addition to .localhistory, when clicked upon in this page says "Showing 1 changed file  with 116 additions and 113 deletions.". Not sure what the big counts of additions/deletions mean

**Comment by birbilis** [comment]
there is a chance those additions/deletions are changes WRONGLY counted in the files (if you see the diff it seems to treat the changes as huge blocks of changed stuff, instead of correctly showing changed lines). Probably related to the issue I reported earlier on today about line ending handling not having been set at the repository

**Comment by panthernet** [comment]
Hmm, that's strange. It marks the whole file as differ.  Haven't encountered similar issues yet :(

**Comment by panthernet** [comment]
Merged successfuly thou.

**Pull request merged**
