### PR TITLE
Patch for issue #6

### PR DESCRIPTION
**Pull request by jorgensigvardsson**
This patch focuses on solving the issue #6. What I have done is the following:
- The existing code for concurrency in AlgorithmBase has been removed
  - It is assumed that the caller controls whether the computation is made concurrent or not
  - Cancellation is made by means of `CancellationToken` objects
- All algorithms have been made cancellable
  - Most algorithms check against the cancellation token. I have tried to make the checks as infrequent as possible - mostly in O(n^2) and above loops. The checks made inside CancellationToken are VERY cheap, so there should be virtually no impact on the performance
- Asynchronous layout is now executed in a `Task` object rather than a `BackgroundWorker`
  - Re-layouts still cancels any ongoing layout task, but will wait for the task's completion
  - UI synchronization is done through the dispatcher's task scheduler, meaning that any exception thrown on the UI thread will be marshaled back to the task, and can no longer crash the application

On the surface, the patch looks big, but it's really not that big. Almost all algorithm files have been touched, but little change has been made in each file. The biggest change is in GraphArea.cs which orchestrates the execution and cancellation of the asynchronous layout operation. I have on purpose not made any cancellation checks in the code paths that execute on the UI. Mainly because I don't want to risk that the control is left in a weird state.

Let me know what you think!

### CODE REVIEW

**Comment by panthernet** [comment]
That's cool! :) I'll take a look asap! All i have to say for now, it would be nice if you will do the following if possible:
1. Mention breaking changes. Changes that can break existing users code, for ex. changes to IExternalLayout interface. So i don't miss them for sure in my changelog and docs :)
2. If you are familiar with METRO it would be super cool to have all this changes in both projects for WPF and METRO :) Code is almost the same for for both of them. Same classes with slightly different implementation of specific methods.  Most differences are in UI visualization routines and templates.

**Comment by jorgensigvardsson** [comment]
Sorry about the interface breakage! I didn't even reflect on that. Never create pull requests while drunk OR tired. :sweat_smile:

As for the metro stuff, I am sorry, but right now I can't even open the project. I think there's a couple of USB stick installs of Windows 8.1 at work. I'll go check if I can snag one today.

Is it possible to pull the pull request? I'm thinking that if I get a hold of a 8.1 stick, I'll fix the metro stuff as well (and test it!).

**Comment by panthernet** [comment]
Well, i never tried to pull a pull or similar things on GitHub :) I think i'll merge it and then you can make new merge request for METRO

**Comment by jorgensigvardsson** [comment]
I hope I didn't break the build!

**Comment by panthernet** [comment]
Looking good so far :)

**Comment by panthernet** [comment]
Oh, i think i've found an issue :) In showcase app in Layouts - Playground if you perform async calc and then change layout algorithm it will throw cancellation request. May be cancellation token isn't refreshed in that case?

**Comment by panthernet** [comment]
Ah, not an issue i suppose :) There is auto recalc on layout algorithm change and it will run silently and being interrupted by manual refresh :) I need to tweak showcase app.

**Comment by jorgensigvardsson** [comment]
Does it stop the application? I can see the exceptions in the debug output, but that is expected, as the cancellation token throws a `OperationCanceledException`. When the layout is performed again, the task that did the earlier layout will be joined/awaited, and a new cancellation source is created (they cannot be reused - which is good because it makes them VERY efficient. Microsoft is employing some pretty nice lock less techniques inside it and the tokens).

Well, I'm off to the office to snag a Windows 8.1 stick!

**Comment by panthernet** [comment]
All looks good again, false alarm! :) I have to redesign ShowcaseApp.WPF logic to display calculation task all the time and exclude any hidden activity.

**Pull request merged**
