### PR TITLE
Drag selection, edge dragging, GraphArea control click events

### PR DESCRIPTION
**Pull request by perturbare**
In my application, I want to have drag selection instead of panning as the unmodified mouse drag behavior for ZoomControl. I added a flag that can be used to achieve this. By default, it will use the original panning behavior. When IsDragSelectByDefault is set to true, dragging without modifier keys will do a drag selection, but holding shift will still pan.

I also wanted the ability to drag an edge and have its connected vertices move with it. To achieve this, I modified some of the EdgeControl and DragBehavior code. An application developer can then tag the connected vertices when an edge is selected and than dragging the edge will update the VertexControl positions. It was necessary to update the OriginalX and OriginalY with each move in order to get the edge based dragging to work correctly.

In a previous pull request (#40), I implemented a Click event for VertexControl. This pull request adds a Click event to EdgeControl and also propagates those events up to GraphArea as VertexClicked and EdgeClicked events.

This pull request supersedes #55, which has been closed.

### CODE REVIEW

**Comment by panthernet** [comment]
Thanks! I'll check it

**Comment by perturbare** [comment]
I made another commit to this branch and pull request. The changes in my latest commit are to implement basic snapping in DragBehavior. There's a comment at the top of the class that is my attempt to describe how to use snapping (and how to use what already existed).

**Comment by perturbare** [comment]
I updated the DynamicGraph page with check boxes to control snapping so you can see an easy demo of it. Only items that are tagged from the SelectVertex() method will snap in that demo page. Please let me know what you think. I'm particularly interested in your feedback on whether it's sufficient to override behavior using attached properties on individual objects. As you'll see in the demo, if you tag the vertex, its snapping behavior will be controlled by the check boxes. If you drag an untagged vertex, its snapping behavior is controlled by the default predicate, which snaps when holding the shift key.

**Comment by panthernet** [comment]
I'd tested it and it is awesome :) Do you have plans to work further in this feature or may i tweak it? I think it needs at least one option to be able to work without the tagging for ones who will want it to be enabled for simple drags.

**Comment by perturbare** [comment]
I'll do some more work on it. I started with the attached property implementation and ended up wishing there was a way to override the behavior globally, without having to set the attached property to achieve different behavior.

**Pull request merged**
